### ISSUE TITLE
com.github.abdularis.buttonprogress.DownloadButtonProgress Class Not Found

### ISSUE THREAD

**Issue by ma-altaiir** [abdularis/Android-Button-Progress#1]
Hi;
Just tried your library, good work but i can not make it work, the lib is imported and shows in external libraries but DownloadButtonProgress Class is not found neither by designer nor in code, only thing appearing is the resource R in your packege !!

**Comment by abdularis** [comment]
Thanks before,
actually I set minifyEnabled to true, and I didn't have any proguard rules applied, so the proguard remove the DownloadButtonProgress class from library,
now you can try it with
implementation 'com.github.abdularis:AndroidButtonProgress:1.0.1'
