### ISSUE TITLE
Attribute Conflict with AndroidX Upgrade

### ISSUE THREAD

**Issue by RowlandOti** [abdularis/Android-Button-Progress#2]
Is it possible that you can fix the below error in the next release?

![capture](https://user-images.githubusercontent.com/8356008/47748335-9b661400-dc9b-11e8-924e-c1ee2a69f12d.PNG)

It requires re-naming the attribute `progress` to something else, to avoid compilation error due to conflicts with similar attirbutes already defined in AndroidX libraries. @abdularis

**Comment by LloydBlv** [comment]
Same problem here, Looking for an update

**Comment by abdularis** [comment]
I'll update the property name soon, thanks for your feedback
