### ISSUE TITLE
In Correct Dependency

### ISSUE THREAD

**Issue by PDshant** [abdularis/Android-Button-Progress#3]
Hello...First of all Nice Library...In your recent update having dependency
 implementation 'com.github.abdularis:AndroidButtonProgress:1.0.1' has mistake that it includes capital letters which causes build failure...After minimizing it project builds succefully...So please correct it to implementation 'com.github.abdularis:androidbuttonprogress:1.0.1'

**Comment by abdularis** [comment]
I updated the readme, thanks
